language: php

php:
  - 5.3
  - 5.4

# cloning a custom zend skeleton application, running composer on it and replacing the module with
# the one that has been checked out.
before_script:
  - cd ..
  - git clone git://github.com/Ocramius/ZendSkeletonApplication.git -b doctrine-orm-module-tests --recursive
  - cd ZendSkeletonApplication
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install --install-suggests
  - rm -rf vendor/doctrine/DoctrineORMModule
  - cp -r ../DoctrineORMModule vendor/doctrine/
  - cd tests

script: phpunit
