language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer install --dev --prefer-source
  - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

script:
  - phpunit
  - php coverage-checker.php clover.xml 60
  - output=$(php php-cs-fixer.phar fix -v --dry-run --level=psr2 ./src/); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;
