sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - DEPS=locked
        - CS_CHECK=true
        - TEST_COVERAGE=true
    - php: 7.2
      env:
        - DEPS=latest
    - php: 7.3
      env:
        - DEPS=lowest
    - php: 7.3
      env:
        - DEPS=locked
    - php: 7.3
      env:
        - DEPS=latest
    - php: 7.4
      env:
        - DEPS=lowest
    - php: 7.4
      env:
        - DEPS=locked
    - php: 7.4
      env:
        - DEPS=latest

before_install:
  - shopt -s expand_aliases
  - alias docker="travis_retry docker-composer run --rm php"
  - alias composer="travis_retry docker-compose run --rm php composer"
  - alias php="travis_retry docker-compose run -e TRAVIS -e TRAVIS_JOB_ID --rm php php"
  - docker-compose build --build-arg PHP_VERSION=${TRAVIS_PHP_VERSION} --build-arg XDEBUG=${TEST_COVERAGE:+1} --no-cache php
  - composer --version
  - php -v
  - php -m

install:
  - php --info
  - composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $DEPS == 'latest' ]]; then composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - docker-compose run --rm php mysql -h mysql -e 'CREATE DATABASE `database`;'
  - docker stty cols 120 && composer show
  - composer show

before_script:
  - rm -Rf .travis/cache

script:
  - docker cp .travis/config/application.config.php config/application.config.php
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then php build/coverage-checker.php build/clover.xml 70 ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - docker cat .travis/run-cli.sh | xargs -L 1 php

after_script:
  - docker rm -Rf config/application.config.php
  - if [[ $TEST_COVERAGE == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then php ocular.phar code-coverage:upload --format=php-clover ./build/clover.xml; fi
